1     REM THE CLASSIC FIZZBUZZ PROGRAM IN GENSHI BASIC
10    DEF FN FIZZPR(IDX, S$) = PRINTL CAT$(IDX, S$)
20    FOR I=1 TO 100 STEP 1
30      IF (I % 15) EQ 0 THEN FIZZPR(I, " FIZZBUZZ")
40      IF (I % 3)  EQ 0 THEN FIZZPR(I, " FIZZ")
50      IF (I % 5)  EQ 0 THEN FIZZPR(I, " BUZZ")
60    ENDFOR
1000  END